spring:
  datasource:
    name: test
    url: jdbc:mysql://139.224.16.177:5522/sms?autoReconnect=true&zeroDateTimeBehavior=convertToNull
    username: poweruser
    password: password
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
mybatis:
  mapperLocations: classpath*:/sql/*.xml
  typeAliasesPackage: com.power.yuneng.sms.domain
server:
  port: 8089
